# Generated by Django 5.2 on 2025-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Negatif'), ('netral', 'Netral')], max_length=10)),
            ],
        ),
    ]
